export const poFormatDataType = [
  { fieldName: "entryDate", label: "Entry Date", id: "entryDate" },
  { fieldName: "brand", label: "Brand", id: "brand" },
  { fieldName: "channel", label: "Channel", id: "channel" },
  { fieldName: "location", label: "Location", id: "location" },
  { fieldName: "poDate", label: "PO Date", id: "poDate" },
  { fieldName: "poNumber", label: "PO Number", id: "poNumber" },
  { fieldName: "srNo", label: "Sr No", id: "srNo" },
  { fieldName: "skuName", label: "SKU Name", id: "skuName" },
  { fieldName: "skuCode", label: "SKU Code", id: "skuCode" },
  { fieldName: "channelSkuCode", label: "Channel SKU Code", id: "channelSkuCode" },
  { fieldName: "qty", label: "Quantity", id: "qty" },
  { fieldName: "gmv", label: "GMV", id: "gmv" },
  { fieldName: "poValue", label: "PO Value", id: "poValue" },
  { fieldName: "actualPoNumber", label: "Actual PO Number", id: "actualPoNumber" },
  { fieldName: "updatedQty", label: "Updated Quantity", id: "updatedQty" },
  { fieldName: "updatedGmv", label: "Updated GMV", id: "updatedGmv" },
  { fieldName: "updatedPoValue", label: "Updated PO Value", id: "updatedPoValue" },
  { fieldName: "facility", label: "Facility", id: "facility" },
  { fieldName: "accountsWorking", label: "Accounts Working", id: "accountsWorking" },
  { fieldName: "channelInwardingQuantity", label: "Channel Inwarding Quantity", id: "channelInwardingQuantity" },
  { fieldName: "workingDate", label: "Working Date", id: "workingDate" },
  { fieldName: "dispatchDate", label: "Dispatch Date", id: "dispatchDate" },
  { fieldName: "currentAppointmentDate", label: "Current Appointment Date", id: "currentAppointmentDate" },
  { fieldName: "statusPlanning", label: "Status Planning", id: "statusPlanning" },
  { fieldName: "statusWarehouse", label: "Status Warehouse", id: "statusWarehouse" },
  { fieldName: "statusLogistics", label: "Status Logistics", id: "statusLogistics" },
  { fieldName: "orderNo", label: "Order No", id: "orderNo" },
  { fieldName: "poNumberInward", label: "PO Number Inward", id: "poNumberInward" },
//   { fieldName: "invoiceLink", label: "Invoice Link", id: "invoiceLink" },
//   { fieldName: "cnLink", label: "CN Link", id: "cnLink" },
  { fieldName: "maxPoEntryCount", label: "Max PO Entry Count", id: "maxPoEntryCount" },
  { fieldName: "poCheck", label: "PO Check", id: "poCheck" },
  { fieldName: "temp", label: "Temp", id: "temp" },
  { fieldName: "inwardPos", label: "Inward POS", id: "inwardPos" },
  { fieldName: "sku", label: "SKU", id: "sku" },
  { fieldName: "uidDb", label: "UID DB", id: "uidDb" },
  { fieldName: "channelType", label: "Channel Type", id: "channelType" },
  { fieldName: "actualWeight", label: "Actual Weight", id: "actualWeight" },
  { fieldName: "check", label: "Check", id: "check" }
];

