export const master_facility_option = [
  "HYP_SRGWHT",
  "HYP_SRBGLR",
  "HYP_SRHYD",
  "HYP_SRKOL",
  "mCaff_Ahmedabad",
  "mCaff_Kolkata2",
  "mCaff_Guwahati",
  "mCaff_Hyderabad2",
  "mCaff_Bangalore2",
  "mCaff_Gurgaon2",
  "mCaff_Mumbai2",
  "HYP_SRGGN",
  "HYP_AHMD",
  "HYP_B2B_MUM2",
  "MUM_Warehouse2"
];

export const master_channel_options = [
    "Amazon",
    "Avenue E-Commerce",
    "BigBasket",
    "Blinkit",
    "Firstcry",
    "Flipkart",
    "Flipkart Grocery", 
    "Flipkart Q-Comm", 
    "D2C",
    "Myntra",
    "Nykaa",
    "Purplle SOR",
    "Reliance Retail (Tira)",
    "Scootsy Cloudstore", 
    "Scootsy Jupiterkart", 
    "Scootsy Logistics", 
    "Scootsy Moksh", 
    "Scootsy PJTJ", 
    "Zepto",
];

export const master_appointment_change_options = [
  {
    remark: "Appointment Miss - Inventory Issue",
    category: "Appointment Miss",
  },
  {
    remark: "Appointment Miss - Logisitc Team",
    category: "Appointment Miss",
  },
  {
    remark: "Appointment Miss - Appointment Not Reschduled",
    category: "Appointment Miss",
  },
  {
    remark: "Appointment Rejected - MRP Issue",
    category: "Appointment Rejected",
  },
  {
    remark: "Appointment shift - Festival/Holiday",
    category: "Appointment Shift",
  },
  {
    remark: "Appointment shift - Cancelled by Channel",
    category: "Appointment Shift",
  },
  {
    remark: "Channel Rejection - Appointment Shift",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Address Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - ASN issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Barcode issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Box Mismatch",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Capacity Full",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Duplicate Order",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - E Way Bill Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - EAN Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Incorrect PO Raised",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Invoice Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Invoice Number Mismatch",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Local Protest",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Natural disasters",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - No Appointment",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Open Box Delivery Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Packinglist Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Partial Delivery",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - PL Uplodaing Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - PO Cancelled",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Revised Qty Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Server Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - SKU Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - SOP Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Tech Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Warehouse Audit",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Warehouse Shifted",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Wrong Invoice Created",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection - Wrongly tagged",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection-Space Issue",
    category: "Channel Rejection",
  },
  {
    remark: "Channel Rejection-Wrong PO",
    category: "Channel Rejection",
  },
  {
    remark: "Courier Miss - Appointment Letter Issue",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Late Reporting",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Local Protest",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Location Untraceable",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Logistics Risk",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - No Info",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Not attempted",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Pincode Issue",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Risky TAT",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Shipment Misrouted",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Traffic Jam/Road Block",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss- Taging Issue",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Box Missplaced/Lost",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Breakdown/Vehicle Issue",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - Intransit delay",
    category: "Courier Miss",
  },
  {
    remark: "Courier Miss - RAD<>Not attempted",
    category: "Courier Miss",
  },
  {
    remark: "Planning/WH - Not Dispatch",
    category: "Planning/WH Miss",
  },
  {
    remark: "Planning/WH - Working Delay",
    category: "Planning/WH Miss",
  },
  {
    remark: "Shipment Rejected - EAN Issue",
    category: "Shipment Rejected",
  },
  {
    remark: "Shipment Rejected - Inwarding Closed",
    category: "Shipment Rejected",
  }
];

export const master_status_planning_options = [
    "Confirmed", // default
    "Not Confirmed", 
    "Cancelled Shipment - Channel", 
    "Cancelled Shipment - Low Value", 
    "Hold",
]

export const master_status_warehouse_options = [
    "Confirmed", // default
    "Picking",
    "Packed",
    "Label Pending", 
    "RTS",
    "Dispatched",
    "Cancelled Shipment - Low Value", 
    "Cancelled Shipment - Channel", 
    "RTO Received", 
    "Internal Transfer",
]

export const master_status_logistics_options = [
    "Confirmed", // default
    "Dispatched",
    "Partner Pickup", 
    "OFD",
    "Delivered POD Pending", 
    "Delivered",
    "RTO Initiated", 
    "RTO Delivered", 
    "Internal Transfer", 
]

export const master_rto_remark_options = [
    "Cancelled Shipment - Channel",
    "Cancelled Shipment - Expired Shipment",
]

export const master_sku_channel_mapping = [
    {
        sku_code:"",
        channel:"",
        channel_code: "",
    }
]

export const master_channel_location_mapping = {
    "Amazon": [
      {location:"AMD2", channelType:"B2C", apptChannel:"yes",	drop_location: "Ahmedabad",},
      {location:"ATX1", channelType:"B2C", apptChannel:"yes",	drop_location: "Ludhiana",},
      {location:"BLR7", channelType:"B2C", apptChannel:"yes",	drop_location: "Bangalore",},
      {location:"BLR8", channelType:"B2C", apptChannel:"yes",	drop_location: "Bangalore",},
      {location:"BOM5", channelType:"B2C", apptChannel:"yes",	drop_location: "Mumbai",},
      {location:"BOM7", channelType:"B2C", apptChannel:"yes",	drop_location: "Mumbai",},
      {location:"CCX1", channelType:"B2C", apptChannel:"yes",	drop_location: "Kolkata",},
      {location:"CJB1", channelType:"B2C", apptChannel:"yes",	drop_location: "Chennai",},
      {location:"DEL4", channelType:"B2C", apptChannel:"yes",	drop_location: "Delhi NCR",}, 
      {location:"DEL5", channelType:"B2C", apptChannel:"yes",	drop_location: "Delhi NCR",}, 
      {location:"DEX3", channelType:"B2C", apptChannel:"yes",	drop_location: "Delhi NCR",}, 
      {location:"DEX8", channelType:"B2C", apptChannel:"yes",	drop_location: "Delhi NCR",}, 
      {location:"GAX1", channelType:"B2C", apptChannel:"yes",	drop_location: "Guwahati",},
      {location:"HYD3", channelType:"B2C", apptChannel:"yes",	drop_location: "Hyderabad",},
      {location:"HYD8", channelType:"B2C", apptChannel:"yes",	drop_location: "Hyderabad",},
      {location:"JPX1", channelType:"B2C", apptChannel:"yes",	drop_location: "Jaipur",},
      {location:"JPX2", channelType:"B2C", apptChannel:"yes",	drop_location: "Jaipur",},
      {location:"LKO1", channelType:"B2C", apptChannel:"yes",	drop_location: "Lucknow",},
      {location:"MAA4", channelType:"B2C", apptChannel:"yes",	drop_location: "Chennai",},
      {location:"PAX1", channelType:"B2C", apptChannel:"yes",	drop_location: "Patna",},
      {location:"PNQ2", channelType:"B2C", apptChannel:"yes",	drop_location: "Pune",},
      {location:"PNQ3", channelType:"B2C", apptChannel:"yes",	drop_location: "Pune",},
      {location:"SIDA", channelType:"B2C", apptChannel:"yes",	drop_location: "SIDA",},
      {location:"CCU1", channelType:"B2C", apptChannel:"yes",	drop_location: "Calicut",},
      {location:"RSOC", channelType:"B2C", apptChannel:"yes",	drop_location: "Kolkata",},
      {location:"REOB", channelType:"B2C", apptChannel:"yes",	drop_location: "REOB",},
      {location:"RSO7", channelType:"B2C", apptChannel:"yes",	drop_location: "Mumbai",},
      {location:"RSO8", channelType:"B2C", apptChannel:"yes",	drop_location: "RSO8",},
      {location:"RSO6", channelType:"B2C", apptChannel:"yes",	drop_location: "RSO6",},
      {location:"RSXE", channelType:"B2C", apptChannel:"yes",	drop_location: "RSXE",},
      {location:"CCX2", channelType:"B2C", apptChannel:"yes",	drop_location: "Kolkata",},
    ],

    "Blinkit": [
      {location: "Ghaziabad", drop_location:"Delhi NCR"},
      {location: "Mumbai M9",	 drop_location:"Mumbai"},
      {location: "Indore",drop_location:"Indore"},
      {location: "Chennai C4" , drop_location:	"Chennai"},
      {location: "Bengaluru B3" , drop_location:	"Bangalore"},
      {location: "Lucknow L4" , drop_location:	"Lucknow"},
      {location: "Mumbai M10" , drop_location:	"Mumbai"},
      {location: "Ghaziabad D3" , drop_location:	"Delhi NCR"},
      {location: "Rajpura", drop_location:	"Rajpura"},
      {location: "Jaipur J2", drop_location: 	"Jaipur"},
      {location: "Ranchi R1" , drop_location:	"Ranchi"},
      {location: "Bengaluru B4" , drop_location:	"Bangalore"},
      {location: "Noida N1", drop_location: 	"Delhi NCR"},
      {location: "Coimbatore C1" , drop_location:	"Coimbatore"},
      {location: "Ludhiana L2", drop_location: "Ludhiana"},
      {location: "Dehradun", drop_location: "Dehradun"},
      {location: "Farukhnagar", drop_location:	"Delhi NCR"},
      {location: "Goa", drop_location:	"Goa"},
      {location: "Nagpur N1" , drop_location:	"Nagpur"},
      {location: "Patna P1" , drop_location:	"Patna"},
      {location: "Varanasi"	, drop_location:"Varanasi"},
      {location: "Kolkata K4" , drop_location:	"Kolkata"},
      {location: "Ahmedabad 2", drop_location:	"Ahmedabad"},
      {location: "Pune P2" , drop_location:	"Pune"},
      {location: "Gurgaon G7", drop_location: 	"Gurgaon"},
      {location: "Hyderabad H2" , drop_location:	"Hyderabad"},
      {location: "Jaipur J3" , drop_location:	"Jaipur"},
      {location: "Hyderabad H3" , drop_location:	"Hyderabad"},
      {location: "Lucknow L5" , drop_location:	"Lucknow"},
      {location: "Guwahati G1" , drop_location:	"Guwahati"},
      {location: "Chennai C5", drop_location: 	"Chennai"},
      {location: "Bhubaneswar B1" , drop_location:	"Bhubaneshwar"},
      {location: "Farukhnagar F2", drop_location: 	"Farukhnagar"},
      {location: "Visakhapatnam V1" , drop_location:	"Visakhapatnam"},
      {location: "Surat S1" , drop_location:	"Surat"},
      {location: "Kundli"	, drop_location:"Delhi NCR"},
      {location: "Mumbai M11" ,	drop_location: "Mumbai"},
      {location: "Bhopal B1" ,	drop_location: "Bhopal"},
    ],

    "Avenue E-Commerce": [
      { location: "Hoodi", channelType: "B2B", apptChannel: "No", drop_location: "Hoodi" },
      { location: "Indore", channelType: "B2B", apptChannel: "No", drop_location: "Indore" },
      { location: "Wagholi FC", channelType: "B2B", apptChannel: "No", drop_location: "Pune" },
      { location: "Bhopal", channelType: "B2B", apptChannel: "No", drop_location: "Bhopal" },
      { location: "Hennur", channelType: "B2B", apptChannel: "No", drop_location: "Hennur" },
      { location: "Surat", channelType: "B2B", apptChannel: "No", drop_location: "Surat" },
      { location: "Vadodara", channelType: "B2B", apptChannel: "No", drop_location: "Vadodara" },
      { location: "Chennai", channelType: "B2B", apptChannel: "No", drop_location: "Chennai" },
      { location: "Kancharapalem", channelType: "B2B", apptChannel: "No", drop_location: "Kancharapalem" },
      { location: "Handewadi FC", channelType: "B2B", apptChannel: "No", drop_location: "Pune" },
      { location: "Palya", channelType: "B2B", apptChannel: "No", drop_location: "Palya" },
      { location: "Yelahanka (Bangalore)", channelType: "B2B", apptChannel: "No", drop_location: "Yelahanka" },
      { location: "Amberpet", channelType: "B2B", apptChannel: "No", drop_location: "Amberpet" },
      { location: "Gurugram", channelType: "B2B", apptChannel: "No", drop_location: "Delhi NCR" },
      { location: "Navi Mumbai", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Taloja FC", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Andheri East", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Palghar", channelType: "B2B", apptChannel: "No", drop_location: "Palghar" },
      { location: "Kanjur Marg", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Mulund FC", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Goregaon West", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Dombivali", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Vashi", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Mira Road FC", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Panvel", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Thane", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Pune", channelType: "B2B", apptChannel: "No", drop_location: "Pune" },
      { location: "Nagpur FC", channelType: "B2B", apptChannel: "No", drop_location: "Nagpur" },
      { location: "Gachibowli", channelType: "B2B", apptChannel: "No", drop_location: "Gachibowli" },
      { location: "Medchal", channelType: "B2B", apptChannel: "No", drop_location: "Medchal" },
      { location: "Ahmedabad", channelType: "B2B", apptChannel: "No", drop_location: "Ahmedabad" },
      { location: "Nashik FC", channelType: "B2B", apptChannel: "No", drop_location: "Nashik" },
      { location: "Sanand", channelType: "B2B", apptChannel: "No", drop_location: "Sanand" },
      { location: "Handewadi", channelType: "B2B", apptChannel: "No", drop_location: "Pune" },
      { location: "Mulund", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Nashik", channelType: "B2B", apptChannel: "No", drop_location: "Nashik" },
      { location: "Mira Road", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Bangalore Hoodi", channelType: "B2B", apptChannel: "No", drop_location: "Hoodi" },
      { location: "Goregaon", channelType: "B2B", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Wagholi", channelType: "B2B", apptChannel: "No", drop_location: "Pune" },
      { location: "Nagpur", channelType: "B2B", apptChannel: "No", drop_location: "Nagpur" },
    ],

    "BigBasket": [
      { location: "Gurgaon", channelType: "B2B", apptChannel: "Yes", drop_location: "Gurgaon" },
      { location: "Kolkata", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Bhiwandi 2", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Bangalore", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Kundli", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Bhiwandi", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Pune", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "Noida", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Ahmedabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Ahmedabad" },
      { location: "Chennai", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" },
      { location: "Mumbai", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Bengaluru B3", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
    ],

    "Firstcry": [
      { location: "Delhi Bijwasan", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Andheri East (Rajmudra)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Kolkata", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Arham International", channelType: "B2B", apptChannel: "Yes", drop_location: "Arham International" },
      { location: "Byrathi (Bangalore)", channelType: "B2B", apptChannel: "Yes", drop_location: "Byrathi" },
      { location: "HSR (Bangalore)", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Jaipur", channelType: "B2B", apptChannel: "Yes", drop_location: "Jaipur" },
      { location: "Pune", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "Laxmi Balaji Enterprises", channelType: "B2B", apptChannel: "Yes", drop_location: "#N/A" },
      { location: "Bangalore", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Mumbai", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Hyderabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Vijayawada", channelType: "B2B", apptChannel: "Yes", drop_location: "Vijayawada" },
      { location: "Medchal", channelType: "B2B", apptChannel: "Yes", drop_location: "Medchal" },
    ],

    "Flipkart": [
      { location: "Sanpka", channelType: "B2C", apptChannel: "Yes", drop_location: "Sanpka" },
      { location: "Mumbai BTS", channelType: "B2C", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Hyderabad", channelType: "B2C", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Jaipur Sanganer", channelType: "B2C", apptChannel: "Yes", drop_location: "Jaipur" },
      { location: "Bangalore Malur", channelType: "B2C", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Kolkata", channelType: "B2C", apptChannel: "Yes", drop_location: "Kolkata" },
    ],

    "Flipkart Grocery": [
      { location: "Ahmedabad (Bavla01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Ahmedabad" },
      { location: "Hyderabad (Pudur01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Delhi NCR1", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Pune (Chakan01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "Nagpur (Hingna01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Nagpur" },
      { location: "Mumbai (Saidham01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Delhi (Dharuhera01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Bangalore (Anekal01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Bangalore (Nelamangala01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Nelamangala" },
      { location: "Kolkata (Panchghara01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Kolkata (Amta01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Chennai (Orakaddu02)", channelType: "B2B", apptChannel: "Yes", drop_location: "Orakaddu" },
      { location: "Chennai (Orakaddu01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Orakaddu" },
      { location: "Chennai (Orakaddu)", channelType: "B2B", apptChannel: "Yes", drop_location: "Orakaddu" },
      { location: "bhubaneswar (mendhasala01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Bhubaneswar" },
      { location: "Bhiwandi (Saidham01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
    ],

    "Flipkart Q-Comm":  [
      { location: "Mumbai (Saidham01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Delhi (Bijwasan)", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Howrah (Uluberia)", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Gurgaon (Binola)", channelType: "B2B", apptChannel: "Yes", drop_location: "Gurgaon" },
      { location: "Bangalore (Anj_BTS_01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Farrukhnagar BTS", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Bhiwandi (Saidham01)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
    ],

    "D2C": [
      { location: "Bangalore - SR", channelType: "D2C", apptChannel: "No", drop_location: "Bangalore" },
      { location: "Hyderabad - SR", channelType: "D2C", apptChannel: "No", drop_location: "Hyderabad" },
      { location: "Gurgaon - SR", channelType: "D2C", apptChannel: "No", drop_location: "Gurgaon" },
      { location: "Kolkata - SR", channelType: "D2C", apptChannel: "No", drop_location: "Kolkata" },
      { location: "Guwahati - SR", channelType: "D2C", apptChannel: "No", drop_location: "Guwahati" },
      { location: "Mumbai2 - DLV", channelType: "D2C", apptChannel: "No", drop_location: "Mumbai" },
      { location: "Ahmedabad - SR", channelType: "D2C", apptChannel: "No", drop_location: "Ahmedabad" },
    ],

    "Myntra": [
      { location: "Gurgaon", channelType: "B2C", apptChannel: "Yes", drop_location: "Gurgaon" },
      { location: "Kolkata", channelType: "B2C", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Bangalore", channelType: "B2C", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Mumbai", channelType: "B2C", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Secunderabad", channelType: "B2C", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Jaipur", channelType: "B2C", apptChannel: "Yes", drop_location: "Jaipur" },
      { location: "Gurgoan", channelType: "B2C", apptChannel: "Yes", drop_location: "Gurgaon" },
    ],

    "Nykaa": [
      { location: "Chennai", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" },
      { location: "Mumbai2", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Bhiwandi", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Kolkata", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Lucknow", channelType: "B2B", apptChannel: "Yes", drop_location: "Lucknow" },
      { location: "Hyderabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Chandigarh", channelType: "B2B", apptChannel: "Yes", drop_location: "Chandigarh" },
      { location: "Tauru", channelType: "B2B", apptChannel: "Yes", drop_location: "Tauru" },
      { location: "DEL2", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Bangalore2", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Kolkata2", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "DEL1", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "Ahmedabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Ahmedabad" },
      { location: "Bangalore BL1", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Guwahati", channelType: "B2B", apptChannel: "Yes", drop_location: "Guwahati" },
      { location: "Patna", channelType: "B2B", apptChannel: "Yes", drop_location: "Patna" },
      { location: "Pune", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "Bangalore", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Mumbai", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Indore", channelType: "B2B", apptChannel: "Yes", drop_location: "Indore" },
    ],

    "Purplle SOR": [
      { location: "Coimbatore", channelType: "B2B", apptChannel: "Yes", drop_location: "Coimbatore" },
      { location: "Mumbai", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Hyderabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Vijaywada", channelType: "B2B", apptChannel: "Yes", drop_location: "Vijayawada" },
      { location: "Ludhiana", channelType: "B2B", apptChannel: "Yes", drop_location: "Ludhiana" },
      { location: "Chennai", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" },
      { location: "Gurgaon", channelType: "B2B", apptChannel: "Yes", drop_location: "Gurgaon" },
      { location: "Kolkata", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Bangalore", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Guwahati", channelType: "B2B", apptChannel: "Yes", drop_location: "Guwahati" },
      { location: "Lucknow", channelType: "B2B", apptChannel: "Yes", drop_location: "Lucknow" },
      { location: "Cochin", channelType: "B2B", apptChannel: "Yes", drop_location: "Cochin" },
      { location: "Bhubaneshwar", channelType: "B2B", apptChannel: "Yes", drop_location: "Bhubaneswar" },
    ],

    "Reliance Retail (Tira)": [
      { location: "Bhiwandi", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Thane", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
    ],

    "Scootsy Cloudstore": [
      { location: "MUM FC22", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" }
    ],

    "Scootsy Jupiterkart": [
      { location: "CHN ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" }
    ],

    "Scootsy Logistics": [
      { location: "Lucknow", channelType: "B2B", apptChannel: "Yes", drop_location: "Lucknow" },
      { location: "Chandigarh", channelType: "B2B", apptChannel: "Yes", drop_location: "Chandigarh" },
      { location: "Ecom(Hyderabad)", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Mumbai", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Chennai", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" },
      { location: "Pune", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "Ahmedabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Ahmedabad" },
      { location: "Jhajjar", channelType: "B2B", apptChannel: "Yes", drop_location: "Jhajjar" },
      { location: "Coimbatore", channelType: "B2B", apptChannel: "Yes", drop_location: "Coimbatore" },
      { location: "Kolkata", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "Gurgaon", channelType: "B2B", apptChannel: "Yes", drop_location: "Gurgaon" },
      { location: "Mumbai (Global Complex)", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "KOC IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Kochi" },
      { location: "LKO IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Lucknow" },
      { location: "BLR IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "BLR ECOM2", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "CHD ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Chandigarh" },
      { location: "PUN DELHIVERY", channelType: "B2B", apptChannel: "Yes", drop_location: "Pune" },
      { location: "KOLKATA ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Kolkata" },
      { location: "DLHY GGNFC9", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "HYD IM2", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "MUM FC22", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "DLHY GGNFC5", channelType: "B2B", apptChannel: "Yes", drop_location: "Delhi NCR" },
      { location: "CBE ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Coimbatore" },
      { location: "CHN ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Chennai" },
      { location: "HYD IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "AHM DELHIVERY", channelType: "B2B", apptChannel: "Yes", drop_location: "Ahmedabad" },
      { location: "MUM IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Jaipur", channelType: "B2B", apptChannel: "Yes", drop_location: "Jaipur" },
      { location: "Mumbai B4", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" },
      { location: "Hyderabad", channelType: "B2B", apptChannel: "Yes", drop_location: "Hyderabad" },
      { location: "Ecom(Bangalore)", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Bangalore Urban", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Bangalore", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Bangalore M1", channelType: "B2B", apptChannel: "Yes", drop_location: "Bangalore" },
      { location: "Mumbai IM1", channelType: "B2B", apptChannel: "Yes", drop_location: "Mumbai" }
    ],

    "Scootsy Moksh": [
      { location: "BLR ECOM2", channelType: "B2B", apptChannel: "No", drop_location: "Bangalore" }
    ],

    "Scootsy PJTJ": [
      { location: "CHD ECOM", channelType: "B2B", apptChannel: "Yes", drop_location: "Chandigarh" }
    ],

    "Zepto": [
      {location:"AMD2", channelType:"B2C", apptChannel:"yes",	drop_location: "Ahmedabad",},
    ],
}

export const master_rejection_reasons = [
    "Appointment Miss - Inventory Issue",
    "Appointment Miss - Logisitc Team",
    "Appointment Miss - Appointment Not Reschduled",
    "Appointment Rejected - MRP Issue",
    "Appointment shift - Festival/Holiday",
    "Appointment shift - Cancelled by Channel",
    "Channel Rejection - Appointment Shift",
    "Channel Rejection - Address Issue",
    "Channel Rejection - ASN issue",
    "Channel Rejection - Barcode issue",
    "Channel Rejection - Box Mismatch",
    "Channel Rejection - Capacity Full",
    "Channel Rejection - Duplicate Order",
    "Channel Rejection - E Way Bill Issue",
    "Channel Rejection - EAN Issue",
    "Channel Rejection - Incorrect PO Raised",
    "Channel Rejection - Invoice Issue",
    "Channel Rejection - Invoice Number Mismatch",
    "Channel Rejection - Local Protest",
    "Channel Rejection - Natural disasters",
    "Channel Rejection - No Appointment",
    "Channel Rejection - Open Box Delivery Issue",
    "Channel Rejection - Packinglist Issue",
    "Channel Rejection - Partial Delivery",
    "Channel Rejection - PL Uplodaing Issue",
    "Channel Rejection - PO Cancelled",
    "Channel Rejection - Revised Qty Issue",
    "Channel Rejection - Server Issue",
    "Channel Rejection - SKU Issue",
    "Channel Rejection - SOP Issue",
    "Channel Rejection - Tech Issue",
    "Channel Rejection - Warehouse Audit",
    "Channel Rejection - Warehouse Shifted",
    "Channel Rejection - Wrong Invoice Created",
    "Channel Rejection - Wrongly tagged",
    "Channel Rejection-Space Issue",
    "Channel Rejection-Wrong PO",
    "Courier Miss - Appointment Letter Issue",
    "Courier Miss - Late Reporting",
    "Courier Miss - Local Protest",
    "Courier Miss - Location Untraceable",
    "Courier Miss - Logistics Risk",
    "Courier Miss - No Info",
    "Courier Miss - Not attempted",
    "Courier Miss - Pincode Issue",
    "Courier Miss - Risky TAT",
    "Courier Miss - Shipment Misrouted",
    "Courier Miss - Traffic Jam/Road Block",
    "Courier Miss- Taging Issue",
    "Courier Miss - Box Missplaced/Lost",
    "Courier Miss - Breakdown/Vehicle Issue",
    "Courier Miss - Intransit delay",
    "Courier Miss - RAD<>Not attempted",
    "Planning/WH - Not Dispatch",
    "Planning/WH - Working Delay",
    "Shipment Rejected - EAN Issue",
    "Shipment Rejected - Inwarding Closed"
]