export const facility_option = [
    "HYP_SRGWHT",
    "HYP_SRBGLR",
    "HYP_SRHYD",
    "HYP_SRKOL",
    "mCaff_Ahmedabad",
    "mCaff_Kolkata2",
    "mCaff_Guwahati",
    "mCaff_Hyderabad2",
    "mCaff_Bangalore2",
    "mCaff_Gurgaon2",
    "mCaff_Mumbai2",
    "HYP_SRGGN",
    "HYP_AHMD",
    "HYP_B2B_MUM2",
    "MUM_Warehouse2"
]

export const rejection_reasons = [
    "Appointment Miss - Inventory Issue",
    "Appointment Miss - Logisitc Team",
    "Appointment Miss - Appointment Not Reschduled",
    "Appointment Rejected - MRP Issue",
    "Appointment shift - Festival/Holiday",
    "Appointment shift - Cancelled by Channel",
    "Channel Rejection - Appointment Shift",
    "Channel Rejection - Address Issue",
    "Channel Rejection - ASN issue",
    "Channel Rejection - Barcode issue",
    "Channel Rejection - Box Mismatch",
    "Channel Rejection - Capacity Full",
    "Channel Rejection - Duplicate Order",
    "Channel Rejection - E Way Bill Issue",
    "Channel Rejection - EAN Issue",
    "Channel Rejection - Incorrect PO Raised",
    "Channel Rejection - Invoice Issue",
    "Channel Rejection - Invoice Number Mismatch",
    "Channel Rejection - Local Protest",
    "Channel Rejection - Natural disasters",
    "Channel Rejection - No Appointment",
    "Channel Rejection - Open Box Delivery Issue",
    "Channel Rejection - Packinglist Issue",
    "Channel Rejection - Partial Delivery",
    "Channel Rejection - PL Uplodaing Issue",
    "Channel Rejection - PO Cancelled",
    "Channel Rejection - Revised Qty Issue",
    "Channel Rejection - Server Issue",
    "Channel Rejection - SKU Issue",
    "Channel Rejection - SOP Issue",
    "Channel Rejection - Tech Issue",
    "Channel Rejection - Warehouse Audit",
    "Channel Rejection - Warehouse Shifted",
    "Channel Rejection - Wrong Invoice Created",
    "Channel Rejection - Wrongly tagged",
    "Channel Rejection-Space Issue",
    "Channel Rejection-Wrong PO",
    "Courier Miss - Appointment Letter Issue",
    "Courier Miss - Late Reporting",
    "Courier Miss - Local Protest",
    "Courier Miss - Location Untraceable",
    "Courier Miss - Logistics Risk",
    "Courier Miss - No Info",
    "Courier Miss - Not attempted",
    "Courier Miss - Pincode Issue",
    "Courier Miss - Risky TAT",
    "Courier Miss - Shipment Misrouted",
    "Courier Miss - Traffic Jam/Road Block",
    "Courier Miss- Taging Issue",
    "Courier Miss - Box Missplaced/Lost",
    "Courier Miss - Breakdown/Vehicle Issue",
    "Courier Miss - Intransit delay",
    "Courier Miss - RAD<>Not attempted",
    "Planning/WH - Not Dispatch",
    "Planning/WH - Working Delay",
    "Shipment Rejected - EAN Issue",
    "Shipment Rejected - Inwarding Closed"
]