export const ratesprkgMapping = [
  { provider: "Airtrans - Air", from: "Mumbai", to: "Ahmedabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Amberpet", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Amritsar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Andhra Pradesh", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Aurangabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Bangalore", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Bhopal", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Bhubaneswar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Chandigarh", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Chennai", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Cochin", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Coimbatore", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Dehradun", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Delhi NCR", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Faridabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Farukhnagar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Gachibowli", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Gangtok", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Ghaziabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Goa", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Gurgaon", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Guwahati", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Haryana", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Hennur", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Hoodi", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Hoskote", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Howrah", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Hyderabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Indore", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Jahingarabad", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Jaipur", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Jalandhar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Jhajjar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Kancharapalem", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Karnataka", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Kolkata", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Lucknow", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Ludhiana", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Medchal", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Mira Road", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Mumbai", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Nagpur", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Noida", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Odisha", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Palghar", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Palya", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Parganas", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Patna", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Pune", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Raipur", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Rajpura", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Ranchi", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Sanand", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Sangli", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Sanpka", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Sikkim", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Surat", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Tamil Nadu", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Tauru", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Uttar Pradesh", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Vadodara", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Varanasi", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Vashi", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Vijayawada", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Visakhapatnam", rate: 65 },
  { provider: "Airtrans - Air", from: "Mumbai", to: "Yelahanka", rate: 65 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Ahmedabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Amberpet", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Amritsar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Andhra Pradesh", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Aurangabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Bangalore", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Bhopal", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Bhubaneswar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Chandigarh", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Chennai", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Cochin", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Coimbatore", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Dehradun", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Delhi NCR", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Faridabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Farukhnagar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Gachibowli", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Gangtok", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Ghaziabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Goa", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Gurgaon", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Guwahati", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Haryana", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Hennur", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Hoodi", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Hoskote", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Howrah", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Hyderabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Indore", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Jahingarabad", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Jaipur", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Jalandhar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Jhajjar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Kancharapalem", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Karnataka", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Kolkata", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Lucknow", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Ludhiana", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Medchal", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Mira Road", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Mumbai", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Nagpur", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Noida", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Odisha", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Palghar", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Palya", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Parganas", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Patna", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Pune", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Raipur", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Rajpura", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Ranchi", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Sanand", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Sangli", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Sanpka", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Sikkim", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Surat", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Tamil Nadu", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Tauru", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Uttar Pradesh", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Vadodara", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Varanasi", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Vashi", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Vijayawada", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Visakhapatnam", rate: 20 },
  { provider: "Airtrans - Train", from: "Mumbai", to: "Yelahanka", rate: 20 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Ahmedabad", rate: 8 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Amberpet", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Amritsar", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Andhra Pradesh", rate: 11 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Aurangabad", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Bangalore", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Bhopal", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Bhubaneswar", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Chandigarh", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Chennai", rate: 11 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Cochin", rate: 14 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Coimbatore", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Dehradun", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Delhi NCR", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Faridabad", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Farukhnagar", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Gachibowli", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Gangtok", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Ghaziabad", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Goa", rate: 12 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Gurgaon", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Guwahati", rate: 22 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Haryana", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Hennur", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Hoodi", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Hoskote", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Howrah", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Hyderabad", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Indore", rate: 9 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Jahingarabad", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Jaipur", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Jalandhar", rate: 14 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Jhajjar", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Kancharapalem", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Karnataka", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Kolkata", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Lucknow", rate: 12 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Ludhiana", rate: 14 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Medchal", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Mira Road", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Mumbai", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Nagpur", rate: 9 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Noida", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Odisha", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Palghar", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Palya", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Parganas", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Patna", rate: 13 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Pune", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Raipur", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Rajpura", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Ranchi", rate: 13 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Sanand", rate: 8 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Sangli", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Sanpka", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Sikkim", rate: 15 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Surat", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Tamil Nadu", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Tauru", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Uttar Pradesh", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Vadodara", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Varanasi", rate: 12 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Vashi", rate: 7 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Vijayawada", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Visakhapatnam", rate: 10 },
  { provider: "Buraq Logistics - PTL", from: "Mumbai", to: "Yelahanka", rate: 10 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Ahmedabad", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Amberpet", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Amritsar", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Andhra Pradesh", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Aurangabad", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Bangalore", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Bhopal", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Bhubaneswar", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Chandigarh", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Chennai", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Cochin", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Coimbatore", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Dehradun", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Delhi NCR", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Faridabad", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Farukhnagar", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Gachibowli", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Gangtok", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Ghaziabad", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Goa", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Gurgaon", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Guwahati", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Haryana", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Hennur", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Hoodi", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Hoskote", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Howrah", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Hyderabad", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Indore", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Jahingarabad", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Jaipur", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Jalandhar", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Jhajjar", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Kancharapalem", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Karnataka", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Kolkata", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Lucknow", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Ludhiana", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Medchal", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Mira Road", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Mumbai", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Nagpur", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Noida", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Odisha", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Palghar", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Palya", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Parganas", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Patna", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Pune", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Raipur", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Rajpura", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Ranchi", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Sanand", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Sangli", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Sanpka", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Sikkim", rate: 15.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Surat", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Tamil Nadu", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Tauru", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Uttar Pradesh", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Vadodara", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Varanasi", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Vashi", rate: 7 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Vijayawada", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Visakhapatnam", rate: 12.5 },
  { provider: "Everest Logistics - PTL", from: "Mumbai", to: "Yelahanka", rate: 12.5 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Ahmedabad", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Amberpet", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Amritsar", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Andhra Pradesh", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Aurangabad", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Bangalore", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Bhopal", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Bhubaneswar", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Chandigarh", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Chennai", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Cochin", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Coimbatore", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Dehradun", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Delhi NCR", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Faridabad", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Farukhnagar", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Gachibowli", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Gangtok", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Ghaziabad", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Goa", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Gurgaon", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Guwahati", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Haryana", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Hennur", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Hoodi", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Hoskote", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Howrah", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Hyderabad", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Indore", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Jahingarabad", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Jaipur", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Jalandhar", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Jhajjar", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Kancharapalem", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Karnataka", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Kolkata", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Lucknow", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Ludhiana", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Medchal", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Mira Road", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Mumbai", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Nagpur", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Noida", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Odisha", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Palghar", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Palya", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Parganas", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Patna", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Pune", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Raipur", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Rajpura", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Ranchi", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Sanand", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Sangli", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Sanpka", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Sikkim", rate: 20 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Surat", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Tamil Nadu", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Tauru", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Uttar Pradesh", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Vadodara", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Varanasi", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Vashi", rate: 12 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Vijayawada", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Visakhapatnam", rate: 15 },
  { provider: "Everest Logistics - Train", from: "Mumbai", to: "Yelahanka", rate: 15 },
  { provider: "Porter - Local", from: "Mumbai", to: "Mumbai", rate: 0 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Ahmedabad", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Amberpet", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Amritsar", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Andhra Pradesh", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Aurangabad", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Bangalore", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Bhopal", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Bhubaneshwar", rate: 15.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Bhubaneswar", rate: 15.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Chandigarh", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Chennai", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Cochin", rate: 12 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Coimbatore", rate: 12 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Dehradun", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Delhi NCR", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Faridabad", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Farukhnagar", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Gachibowli", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Gangtok", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Ghaziabad", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Goa", rate: 8.4 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Gurgaon", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Guwahati", rate: 18.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Haryana", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Hennur", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Hoodi", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Hoskote", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Howrah", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Hyderabad", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Indore", rate: 9 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Jahingarabad", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Jaipur", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Jalandhar", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Jhajjar", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Kancharapalem", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Karnataka", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Kolkata", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Lucknow", rate: 12 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Ludhiana", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Medchal", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Mira Road", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Mumbai", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Nagpur", rate: 7.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Noida", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Odisha", rate: 15.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Palghar", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Palya", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Parganas", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Patna", rate: 15 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Pune", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Raipur", rate: 15.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Rajpura", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Ranchi", rate: 15 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Sanand", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Sangli", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Sanpka", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Sikkim", rate: 13.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Surat", rate: 7.8 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Tamil Nadu", rate: 12 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Tauru", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Uttar Pradesh", rate: 10.2 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Vadodara", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Varanasi", rate: 12 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Vashi", rate: 6.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Vijayawada", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Visakhapatnam", rate: 9.6 },
  { provider: "Rivigo - PTL", from: "Mumbai", to: "Yelahanka", rate: 9.6 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Ahmedabad", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Amberpet", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Amritsar", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Andhra Pradesh", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Aurangabad", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Bangalore", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Bhopal", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Bhubaneshwar", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Bhubaneswar", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Chandigarh", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Chennai", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Cochin", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Coimbatore", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Dehradun", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Delhi NCR", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Faridabad", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Farukhnagar", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Gachibowli", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Gangtok", rate: 17.6 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Ghaziabad", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Goa", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Gurgaon", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Guwahati", rate: 17.6 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Haryana", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Hennur", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Hoodi", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Hoskote", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Howrah", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Hyderabad", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Indore", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Jahingarabad", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Jaipur", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Jalandhar", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Jhajjar", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Kancharapalem", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Karnataka", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Kolkata", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Lucknow", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Ludhiana", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Medchal", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Mira Road", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Mumbai", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Nagpur", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Noida", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Odisha", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Palghar", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Palya", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Parganas", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Patna", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Pune", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Raipur", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Rajpura", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Ranchi", rate: 11 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Sanand", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Sangli", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Sanpka", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Sikkim", rate: 17.6 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Surat", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Tamil Nadu", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Tauru", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Uttar Pradesh", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Vadodara", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Varanasi", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Vashi", rate: 6.49 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Vijayawada", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Visakhapatnam", rate: 8.25 },
  { provider: "Shiprocket - PTL", from: "Mumbai", to: "Yelahanka", rate: 8.25 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Ahmedabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Amberpet", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Amritsar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Andhra Pradesh", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Aurangabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Bangalore", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Bhopal", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Bhubaneswar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Chandigarh", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Chennai", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Cochin", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Coimbatore", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Dehradun", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Delhi NCR", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Faridabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Farukhnagar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Gachibowli", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Gangtok", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Ghaziabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Goa", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Gurgaon", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Guwahati", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Haryana", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Hennur", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Hoodi", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Hoskote", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Howrah", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Hyderabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Indore", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Jahingarabad", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Jaipur", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Jalandhar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Jhajjar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Kancharapalem", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Karnataka", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Kolkata", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Lucknow", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Ludhiana", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Medchal", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Mira Road", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Mumbai", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Nagpur", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Noida", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Odisha", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Palghar", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Palya", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Parganas", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Patna", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Pune", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Raipur", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Rajpura", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Ranchi", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Sanand", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Sangli", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Sanpka", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Sikkim", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Surat", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Tamil Nadu", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Tauru", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Uttar Pradesh", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Vadodara", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Varanasi", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Vashi", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Vijayawada", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Visakhapatnam", rate: 75 },
  { provider: "Sitics Logistics - Air", from: "Mumbai", to: "Yelahanka", rate: 75 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Ahmedabad", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Amberpet", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Amritsar", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Andhra Pradesh", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Arham International", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Aurangabad", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Bangalore", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Bhopal", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Bhubaneshwar", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Bhubaneswar", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Bilaspur", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Chandigarh", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Chennai", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Cochin", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Coimbatore", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Dehradun", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Delhi NCR", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Faridabad", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Farukhnagar", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Gachibowli", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Gangtok", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Ghaziabad", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Goa", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Gurgaon", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Guwahati", rate: 15 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Haryana", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hennur", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hoodi", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hooghly", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hoskote", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Howrah", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hyderabad", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Hyderbad", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Indore", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Jahingarabad", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Jaipur", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Jalandhar", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Jhajjar", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Kancharapalem", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Karnataka", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Kerala", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Kochi", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Kolkata", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Lucknow", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Ludhiana", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Medchal", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Mira Road", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Mumbai", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Nagpur", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Nashik", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Noida", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Odisha", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Palghar", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Palya", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Parganas", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Patna", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Pune", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Raipur", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Rajpura", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Ranchi", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Sanand", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Sangli", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Sanpka", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Sikkim", rate: 11 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Surat", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Tamil Nadu", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Tauru", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Uttar Pradesh", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Vadodara", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Varanasi", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Vashi", rate: 6.5 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Vijayawada", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Visakhapatnam", rate: 8 },
  { provider: "Sitics Logistics - PTL", from: "Mumbai", to: "Yelahanka", rate: 8 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Ahmedabad", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Amberpet", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Amritsar", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Andhra Pradesh", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Aurangabad", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Bangalore", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Bhopal", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Bhubaneshwar", rate: 30 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Bhubaneswar", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Chandigarh", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Chennai", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Cochin", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Coimbatore", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Dehradun", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Delhi NCR", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Faridabad", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Farukhnagar", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Gachibowli", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Gangtok", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Ghaziabad", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Goa", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Gurgaon", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Guwahati", rate: 30 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Haryana", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Hennur", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Hoodi", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Hoskote", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Howrah", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Hyderabad", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Indore", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Jahingarabad", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Jaipur", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Jalandhar", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Jhajjar", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Kancharapalem", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Karnataka", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Kolkata", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Lucknow", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Ludhiana", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Medchal", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Mira Road", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Mumbai", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Nagpur", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Noida", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Odisha", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Palghar", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Palya", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Parganas", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Patna", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Pune", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Raipur", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Rajpura", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Ranchi", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Sanand", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Sangli", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Sanpka", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Sikkim", rate: 30 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Surat", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Tamil Nadu", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Tauru", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Uttar Pradesh", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Vadodara", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Varanasi", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Vashi", rate: 15 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Vijayawada", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Visakhapatnam", rate: 20 },
  { provider: "Sitics Logistics - Train", from: "Mumbai", to: "Yelahanka", rate: 20 }
]


export function getRates(partner, fromLoc, toLoc) {
  if (!partner || !fromLoc || !toLoc) return 0;

  const entry = ratesprkgMapping.find(
    (item) =>
      item.provider === partner &&
      item.from === fromLoc &&
      item.to === toLoc
  );

  return entry ? entry.rate : 0;
}
