export const poFormatDataType = [
    { fieldName: "shipmentOrderId", label: "Shipment UID", },
    { fieldName: "entryDate", label: "Entry Date", },
    { fieldName: "poDate", label: "PO Date", },
    { fieldName: "facility", label: "Facility", },
    { fieldName: "channel", label: "Channel", },
    { fieldName: "location", label: "Location", },
    { fieldName: "poNumber", label: "PO Number", },
    { fieldName: "brandName", label: "Brand", },
    { fieldName: "srNo", label: "Sr No", },
    { fieldName: "skuName", label: "SKU Name", },
    { fieldName: "skuCode", label: "SKU Code", },
    { fieldName: "channelSkuCode", label: "Channel SKU Code", },
    { fieldName: "qty", label: "Quantity", },
    { fieldName: "gmv", label: "GMV", },
    { fieldName: "poValue", label: "PO Value", },
    { fieldName: "updatedQty", label: "Updated Quantity", },
    { fieldName: "updatedGmv", label: "Updated GMV", },
    { fieldName: "updatedPoValue", label: "Updated PO Value", },
    { fieldName: "productWeight", label: "Product Weight", }, // doubtfull
    { fieldName: "workingDate", label: "Working Date", },
    { fieldName: "dispatchDate", label: "Dispatch Date", },
    { fieldName: "currentAppointmentDate", label: "Current Appointment Date", },
    { fieldName: "statusPlanning", label: "Status Planning", },
    { fieldName: "statusWarehouse", label: "Status Warehouse", },
    { fieldName: "statusLogistics", label: "Status Logistics", },
];

export const shipmentFormatDataType = [
    { fieldName: "uid", label: "UID" },
    { fieldName: "entryDate", label: "Entry Date" },
    { fieldName: "poDate", label: "PO Date" },
    { fieldName: "facility", label: "Facility" },
    { fieldName: "channel", label: "Channel" },
    { fieldName: "location", label: "Location" },
    { fieldName: "poNumber", label: "PO Number" },
    { fieldName: "totalUnits", label: "Total Units" },
    { fieldName: "remarksPlanning", label: "Remarks (Planning)" },
    { fieldName: "specialRemarksCOPT", label: "Special Remarks (COPT)" },
    { fieldName: "newShipmentReference", label: "New Shipment Reference" },
    { fieldName: "statusPlanning", label: "Status (Planning)" },
    { fieldName: "statusWarehouse", label: "Status (Warehouse)" },
    { fieldName: "statusLogistics", label: "Status (Logistics)" },
    { fieldName: "channelInwardingRemarks", label: "Channel Inwarding Remarks" },
    { fieldName: "dispatchRemarksLogistics", label: "Dispatch Remarks (Logistics)" },
    { fieldName: "dispatchRemarksWarehouse", label: "Dispatch Remarks (Warehouse)" },
    { fieldName: "dispatchDateTentative", label: "Dispatch Date - Tentative (Planning)" },
    { fieldName: "workingDatePlanner", label: "Working Date" },
    { fieldName: "rtsDate", label: "RTS Date" },
    { fieldName: "dispatchDate", label: "Dispatch Date" },
    { fieldName: "currentAppointmentDate", label: "Current Appointment Date" },
    { fieldName: "firstAppointmentDateCOPT", label: "First Appointment Date" },
    { fieldName: "noOfBoxes", label: "No of Boxes" },
    { fieldName: "orderNo1", label: "Order No 1" },
    { fieldName: "orderNo2", label: "Order No 2" },
    { fieldName: "orderNo3", label: "Order No 3" },
    { fieldName: "poNumberInwardCWH", label: "PO Number (Inward - CWH)" },
    { fieldName: "pickListNo", label: "Pick List No" },
    { fieldName: "workingTypeWarehouse", label: "Working Type (Warehouse)" },
    { fieldName: "inventoryRemarksWarehouse", label: "Inventory Remarks (Warehouse)" },
    { fieldName: "b2bWorkingTeamRemarks", label: "B2B Working Team Remarks" },
    { fieldName: "volumetricWeight", label: "Volumetric Weight" },
    { fieldName: "channelType", label: "Channel Type" },
    { fieldName: "firstTransporter", label: "1st Transporter (First Mile)" },
    { fieldName: "firstDocketNo", label: "1st Docket No/ Vehicle Number (First Mile)" },
    { fieldName: "secondTransporter", label: "2nd Transporter (Mid Mile)" },
    { fieldName: "secondDocketNo", label: "2nd Docket No/ Vehicle Number (Mid Mile)" },
    { fieldName: "thirdTransporter", label: "3rd Transporter (Last Mile)" },
    { fieldName: "thirdDocketNo", label: "3rd Docket No/ Vehicle Number (Last Mile)" },
    { fieldName: "appointmentLetter", label: "Appointment Letter/STN" },
    { fieldName: "labelsLink", label: "PO Expiry Date" },
    { fieldName: "invoiceDate", label: "Invoice Date" },
    { fieldName: "invoiceLink", label: "Invoice Link" },
    { fieldName: "cnLink", label: "CN Link" },
    { fieldName: "ewayLink", label: "E-Way Link" },
    { fieldName: "invoiceValue", label: "Invoice Value (Check with Invoice Link)" },
    { fieldName: "remarksAccountsTeam", label: "Remarks by Accounts Team" },
    { fieldName: "invoiceChallanNumber", label: "Invoice / Challan Number" },
    { fieldName: "invoiceCheckedBy", label: "Invoice Checked By" },
    { fieldName: "customerCode", label: "Customer Code" },
    { fieldName: "poEntryCount", label: "PO Entry Count" },
    { fieldName: "deliveryDate", label: "Delivery Date" },
    { fieldName: "rescheduleLag", label: "Reschedule Lag (Remarks)" },
    { fieldName: "finalRemarks", label: "Final Remarks" },
    { fieldName: "actualWeight", label: "Shipment Weight" },
    { fieldName: "physicalWeight", label: "Chargable Weight" },
    { fieldName: "deliveryCharges", label: "Delivery Charges" },
    { fieldName: "halting", label: "halting" },
    { fieldName: "unloadingCharges", label: "Unloading Charges" },
    { fieldName: "dedicatedVehicle", label: "Dedicated Vehicle" },
    { fieldName: "otherCharges", label: "Other Charges" },
    { fieldName: "tat", label: "TAT" },
    { fieldName: "criticalDispatchDate", label: "Critical Dispatch Date" },
    { fieldName: "rpk", label: "Rates/kg" },
    { fieldName: "deliveryType", label: "DeliveryType" },
    { fieldName: "appointmentShootedDate", label: "Appointment Shooted Date" },
    { fieldName: "appointmentRequestedDate", label: "Appointment Requested Date" },
    { fieldName: "remarksWarehouse", label: "Remarks (Warehouse)" },
];


export const shipmentStatusDataType = [
  { fieldName: "uid", label: "UID" },
  { fieldName: "entryDate", label: "Entry Date" },
  { fieldName: "poDate", label: "PO Date" },
  { fieldName: "facility",label: "Facility" },
  { fieldName: "channel",label: "Channel" },
  { fieldName: "location",label: "Location" },
  { fieldName: "poNumber", label: "PO Number" },
  { fieldName: "totalUnits", label: "Total Units" },
  { fieldName: "remarksPlanning", label: "Remarks (Planning)" },
  { fieldName: "specialRemarksCOPT", label: "Special Remarks (COPT)" },
  { fieldName: "newShipmentReference", label: "New Shipment Reference" },
  { fieldName: "statusPlanning",label: "Status (Planning)" },
  { fieldName: "statusWarehouse",label: "Status (Warehouse)" },
  { fieldName: "statusLogistics",label: "Status (Logistics)" },
  { fieldName: "channelInwardingRemarks", label: "Channel Inwarding Remarks" },
  { fieldName: "dispatchRemarksLogistics", label: "Dispatch Remarks (Logistics)" },
  { fieldName: "dispatchRemarksWarehouse", label: "Dispatch Remarks (Warehouse)" },
  { fieldName: "dispatchDateTentative", label: "Dispatch Date - Tentative (Planning)" },
  { fieldName: "workingDatePlanner", label: "Working Date" },
  { fieldName: "rtsDate", label: "RTS Date" },
  { fieldName: "dispatchDate", label: "Dispatch Date" },
  { fieldName: "currentAppointmentDate", label: "Current Appointment Date" },
  { fieldName: "firstAppointmentDateCOPT", label: "First Appointment Date" },
  { fieldName: "noOfBoxes", label: "No of Boxes",},
  { fieldName: "orderNo1", label: "Order No 1" },
  { fieldName: "orderNo2", label: "Order No 2" },
  { fieldName: "orderNo3", label: "Order No 3" },
  { fieldName: "poNumberInwardCWH", label: "PO Number (Inward - CWH)" },
  { fieldName: "pickListNo", label: "Pick List No" },
  { fieldName: "workingTypeWarehouse", label: "Working Type (Warehouse)" },
  { fieldName: "inventoryRemarksWarehouse", label: "Inventory Remarks (Warehouse)" },
  { fieldName: "b2bWorkingTeamRemarks", label: "B2B Working Team Remarks" },
  { fieldName: "volumetricWeight", label: "Volumetric Weight" },
  { fieldName: "channelType", label: "Channel Type" },
  { fieldName: "firstTransporter", label: "1st Transporter (First Mile)" },
  { fieldName: "firstDocketNo", label: "1st Docket No/ Vehicle Number (First Mile)" },
  { fieldName: "secondTransporter", label: "2nd Transporter (Mid Mile)" },
  { fieldName: "secondDocketNo", label: "2nd Docket No/ Vehicle Number (Mid Mile)" },
  { fieldName: "thirdTransporter", label: "3rd Transporter (Last Mile)"},
  { fieldName: "thirdDocketNo", label: "3rd Docket No/ Vehicle Number (Last Mile)" },
  { fieldName: "appointmentLetter", label: "Appointment Letter/STN" },    
  { fieldName: "labelsLink", label: "PO Expiry Date" },
  { fieldName: "invoiceDate", label: "Invoice Date" },
  { fieldName: "invoiceLink", label: "Invoice Link" },
  { fieldName: "cnLink", label: "CN Link" },
  { fieldName: "ewayLink", label: "E-Way Link" },
  { fieldName: "invoiceValue", label: "Invoice Value (Check with Invoice Link)" },
  { fieldName: "remarksAccountsTeam", label: "Remarks by Accounts Team" },
  { fieldName: "invoiceChallanNumber", label: "Invoice / Challan Number" },
  { fieldName: "invoiceCheckedBy", label: "Invoice Checked By" },
  { fieldName: "customerCode", label: "Customer Code" },
  { fieldName: "poEntryCount", label: "PO Entry Count" },
  { fieldName: "deliveryDate", label: "Delivery Date" },
  { fieldName: "rescheduleLag", label: "Reschedule Lag (Remarks)" },
  { fieldName: "finalRemarks", label: "Final Remarks" },
  { fieldName: "actualWeight", label: "Shipment Weight" },
  // { fieldName: "updatedGmv", label: "Updated GMV", id: "updatedGmv", type: "number" },
  { fieldName: "physicalWeight", label: "Chargable Weight" },

  // misc charges field
  {fieldName:"deliveryCharges", label: "Delivery Charges" },
  {fieldName:"halting", label: "halting" },
  {fieldName:"unloadingCharges", label: "Unloading Charges" },
  {fieldName:"dedicatedVehicle", label: "Dedicated Vehicle" },
  {fieldName:"otherCharges", label: "Other Charges" },
  // files field
  { fieldName: "document", label: "Document"},
  { fieldName: "proofOfDispatch", label: "Proof Of Dispatch"},
  { fieldName: "proofOfDelivery", label: "Proof Of Delivery"},
  // some new fields
  { fieldName: "tat", label: "TAT" },
  { fieldName: "criticalDispatchDate", label: "Critical Dispatch Date" },
  { fieldName: "rpk", label: "Rates/kg" },
  // delivery type
  { fieldName: "deliveryType", label: "DeliveryType" },
  { fieldName: "statusActive", label: "Status (Active/Inactive)" },
  { fieldName: "appointmentShootedDate", label: "Appointment Shooted Date" },
  { fieldName: "appointmentRequestedDate", label: "Appointment Requested Date" },
  { fieldName: "remarksWarehouse", label: "Remarks (Warehouse)" },

];
