export const poFormatDataType = [
    { fieldName: "shipmentOrderId", label: "Shipment UID", },
    { fieldName: "entryDate", label: "Entry Date", },
    { fieldName: "poDate", label: "PO Date", },
    { fieldName: "facility", label: "Facility", },
    { fieldName: "channel", label: "Channel", },
    { fieldName: "location", label: "Location", },
    { fieldName: "poNumber", label: "PO Number", },
    { fieldName: "brandName", label: "Brand", },
    { fieldName: "srNo", label: "Sr No", },
    { fieldName: "skuName", label: "SKU Name", },
    { fieldName: "skuCode", label: "SKU Code", },
    { fieldName: "channelSkuCode", label: "Channel SKU Code", },
    { fieldName: "qty", label: "Quantity", },
    { fieldName: "gmv", label: "GMV", },
    { fieldName: "poValue", label: "PO Value", },
    { fieldName: "updatedQty", label: "Updated Quantity", },
    { fieldName: "updatedGmv", label: "Updated GMV", },
    { fieldName: "updatedPoValue", label: "Updated PO Value", },
    { fieldName: "productWeight", label: "Product Weight", }, // doubtfull
    { fieldName: "workingDate", label: "Working Date", },
    { fieldName: "dispatchDate", label: "Dispatch Date", },
    { fieldName: "currentAppointmentDate", label: "Current Appointment Date", },
    { fieldName: "statusPlanning", label: "Status Planning", },
    { fieldName: "statusWarehouse", label: "Status Warehouse", },
    { fieldName: "statusLogistics", label: "Status Logistics", },
];	